# Site settings
title: Opinions and thoughts of Daniel Hoherd
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a test site for playing with Jekyll on Github Pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danielhoherd.github.io" # the base hostname & protocol for your site
github_username:  danielhoherd

# Build settings
markdown: kramdown
